7-file

diff --git a/io_redirections_and_filters/7-file b/io_redirections_and_filters/7-file
--- a/io_redirections_and_filters/7-file
+++ b/io_redirections_and_filters/7-file
@@ -1,2 +1,17 @@
 #!/bin/bash
-echo "Best School" > \*\\'"Best School"\'\\*$\?\*\*\*\*\*:)
+
+# Define the file name
+file_name='\*\\\'"Best School"\\\'\*$?******:)'
+
+# Define the text content
+text_content="Best School"
+
+# Create the file with the desired name and content
+echo -e "$text_content\n" > "$file_name"
+
+# Check if the file was created successfully
+if [ -e "$file_name" ]; then
+    echo "File '$file_name' created successfully."
+else
+    echo "File creation failed."
+fi
